In [1]:
import theano
from theano import tensor as T
import lasagne
from lasagne.layers import *
import numpy as np

In [2]:
def net():
    l_in = InputLayer((None, 16, 28, 28))
    l_conv = Conv2DLayer(l_in, num_filters=512, filter_size=5)
    return l_conv

In [3]:
l_out = net()

In [4]:
X = T.tensor4('X')
net_out = get_output(l_out, X)

In [5]:
get_out = theano.function([X], net_out)

In [6]:
fake_data = np.random.normal(0, 1, size=(1, 16, 28, 28))

In [7]:
latent_rep = get_out(fake_data)[0]
latent_rep.shape

(512, 24, 24)

In [8]:
latent_vectors=[]
for i in range(0, latent_rep.shape[1]):
    for j in range(0, latent_rep.shape[2]):
        #print latent_rep[:,i,j].shape
        latent_vectors.append(latent_rep[:,i,j])

In [9]:
latent_vectors = np.asarray(latent_vectors)
latent_vectors.shape

(576, 512)

We now have 24*24=576 vectors of size 512

In [10]:
from sklearn.manifold import TSNE

In [15]:
model = TSNE(n_components=20, random_state=0)

In [ ]:
model.fit_transform(latent_vectors+0.01)

In [47]:
np.sum(np.isinf(latent_vectors))

0

In [56]:
np.isnan(latent_vectors).any()

False